# PATHS:
# define paths for your data
raw_data_path : "interbed/files/raw"
pickled_data_path : "interbed/files/embeds"

# length of files in s
length_of_file: 342

# PLOTTING:
# heading for main interactive plot
title : "UMAP Embedding"

# MODEL:
# relevant files for the model
checkpoint : "interbed/vggish/vggish_model.ckpt"
pca_params : "interbed/vggish/vggish_pca_params.npz"