# PATHS:
# define paths for your data
raw_data_path : "data/raw_files"
pickled_data_path : "data/pickles"

# length of files in s
length_of_file: 342

# PLOTTING:
# heading for main interactive plot
title : "UMAP Embedding"

# MODEL:
# relevant files for the model
checkpoint : "vggish_model.ckpt"
pca_params : "vggish_pca_params.npz"