# PATHS:
# define paths for your data
raw_data_path : "data/examples"
pickled_data_path : "data/pickles"

# PLOTTING:
# heading for main interactive plot
title : "UMAP Embedding"

# MODEL:
# relevant files for the model
checkpoint : "vggish_model.ckpt"
pca_params : "vggish_pca_params.npz"