## MAIN VARS ##
# PATHS:
# define paths for your data
raw_data_path :       "inemviz/files/raw/"
pickled_data_path :   "inemviz/files/embeds/"

# length of files in s
length_of_file:       729.6

# PLOTTING:
# heading for main interactive plot
title :               "UMAP Embedding"

# MODEL:
# relevant files for the model
checkpoint :          "inemviz/vggish/vggish_model.ckpt"
pca_params :          "inemviz/vggish/vggish_pca_params.npz"


## HELPER VARS ##
# preprocessing configurations
preproc:
  # main parent directory containing all annotatoin files
  annots_path:        '/home/vincent/Code/MA/Daten/Catherine_annotations'
  sound_files_path:   '/media/vincent/Seagate Backup Plus Drive/VINCENT_RawData'
  downsample_sr:      2000
  downsample:          True
  model_sr:           16000
  model_time_length:  0.96