## MAIN VARS ##

# PATHS:
# define paths for your data, these are the standard directories, if you 
# used the file condenser. If you do not have annotated data, and all of your
# sound files are in one directory, change accordingly
audio_dir :       "ievad/files/audio/humpbacks"

# fixed path, embeddings will be stored here, DO NOT CHANGE
embed_parent_dir :   "ievad/files/embeds"
umap_parent_dir :   "ievad/files/umap_embeds"

# sample rate
sr : 16000

# embedding model name
embedding_model: 'aves'

# length limitation for condensed file
segs_lim:             1500

# PLOTTING:
# heading for main interactive plot
title :               "UMAP Embedding"
spec_win_len:         1024
umap_height:          900
spec_height:          800
f_min:                50

# PLAYBACK:
# amplify audio to make audible
amp:                  5

# UMAP settings
n_neighbors : 15
n_components : 2
metric : 'euclidean'
random_state: 42

# CONDENSER:
dt_format_std:        False
dt_format:            '%Y%m%d%H%M%S'

## HELPER VARS ##
# preprocessing configurations
preproc:
  # main parent directory containing all annotation files
  annots_path:        'ievad/files/raw/annots'
  # annots_path:        '/home/vincent/Code/MA/generated_annotations/for_umap'
  # main parent directory containing all sound files
  sound_files_path:   'ievad/files/raw/uncondensed'
  # sound_files_path:   '/media/vincent/Expansion/NOAA/NRS08_20162018_new20220711'
  # set to lowest sample rate in your dataset, to ensure comparability
  downsample_sr:      16000
  resamp_size:        16000
  # if you don't want to downsample the data to a common sample rate, set to 'False'
  downsample:         True

  ## Fixed model parameters, do not change
  model_sr:           16000
  model_time_length:  0.96
  # model_sr:           16000
  # model_time_length:  0.96

